name: bourse_casablanca
description: "Bourse Casablanca"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.12.0

dependencies:
  flutter:
    sdk: flutter
  fl_chart: ^0.69.0
  flutter_animate: ^4.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
