"""baseline: schema as deployed 2026-07

Revision ID: 50c59b463e1e
Revises: 
Create Date: 2026-07-16 16:32:55.031979

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '50c59b463e1e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analyst_performance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('analyst', sa.String(length=32), nullable=False),
    sa.Column('horizon', sa.String(length=16), nullable=False),
    sa.Column('sample_size', sa.Integer(), nullable=False),
    sa.Column('hit_rate', sa.Float(), nullable=True),
    sa.Column('brier_score', sa.Float(), nullable=True),
    sa.Column('calibration_error', sa.Float(), nullable=True),
    sa.Column('precision', sa.Float(), nullable=True),
    sa.Column('recall', sa.Float(), nullable=True),
    sa.Column('confidence_multiplier', sa.Float(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('analyst', 'horizon', name='uq_analyst_horizon')
    )
    with op.batch_alter_table('analyst_performance', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_analyst_performance_analyst'), ['analyst'], unique=False)
        batch_op.create_index(batch_op.f('ix_analyst_performance_horizon'), ['horizon'], unique=False)

    op.create_table('macro_indicators',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('indicator', sa.String(length=48), nullable=False),
    sa.Column('as_of', sa.DateTime(timezone=True), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=16), nullable=True),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('collected_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('indicator', 'as_of', 'source', name='uq_macro_observation')
    )
    with op.batch_alter_table('macro_indicators', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_macro_indicators_as_of'), ['as_of'], unique=False)
        batch_op.create_index(batch_op.f('ix_macro_indicators_indicator'), ['indicator'], unique=False)

    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notifications_created_at'), ['created_at'], unique=False)

    op.create_table('push_subscriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('endpoint', sa.Text(), nullable=False),
    sa.Column('p256dh', sa.String(length=255), nullable=False),
    sa.Column('auth', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('endpoint', name='uq_push_endpoint')
    )
    op.create_table('stocks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=False),
    sa.Column('sector', sa.String(length=128), nullable=True),
    sa.Column('source', sa.String(length=64), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('stocks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stocks_company_name'), ['company_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_stocks_symbol'), ['symbol'], unique=True)

    op.create_table('alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stock_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('event_key', sa.String(length=255), nullable=False),
    sa.Column('alert_type', sa.String(length=64), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('sent', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['stock_id'], ['stocks.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stock_id', 'event_key', name='uq_alert_event')
    )
    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_alerts_alert_type'), ['alert_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_alerts_event_key'), ['event_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_alerts_stock_id'), ['stock_id'], unique=False)

    op.create_table('analysis_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stock_id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('horizon_focus', sa.String(length=16), nullable=False),
    sa.Column('engine_version', sa.String(length=16), nullable=False),
    sa.Column('thesis_hash', sa.String(length=64), nullable=False),
    sa.Column('recommendation_short', sa.String(length=32), nullable=True),
    sa.Column('recommendation_medium', sa.String(length=32), nullable=True),
    sa.Column('recommendation_long', sa.String(length=32), nullable=True),
    sa.Column('confidence_short', sa.Float(), nullable=True),
    sa.Column('confidence_medium', sa.Float(), nullable=True),
    sa.Column('confidence_long', sa.Float(), nullable=True),
    sa.Column('risk_score', sa.Float(), nullable=True),
    sa.Column('price_at_report', sa.Float(), nullable=True),
    sa.Column('report_json', sa.Text(), nullable=False),
    sa.Column('narrative', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['stock_id'], ['stocks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('analysis_reports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_analysis_reports_engine_version'), ['engine_version'], unique=False)
        batch_op.create_index(batch_op.f('ix_analysis_reports_generated_at'), ['generated_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_analysis_reports_horizon_focus'), ['horizon_focus'], unique=False)
        batch_op.create_index(batch_op.f('ix_analysis_reports_stock_id'), ['stock_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_analysis_reports_symbol'), ['symbol'], unique=False)
        batch_op.create_index(batch_op.f('ix_analysis_reports_thesis_hash'), ['thesis_hash'], unique=False)

    op.create_table('company_knowledge',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stock_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=48), nullable=False),
    sa.Column('key', sa.String(length=128), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('fact_hash', sa.String(length=64), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('first_seen', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('last_seen', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['stock_id'], ['stocks.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stock_id', 'fact_hash', name='uq_knowledge_fact')
    )
    with op.batch_alter_table('company_knowledge', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_company_knowledge_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_company_knowledge_fact_hash'), ['fact_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_company_knowledge_stock_id'), ['stock_id'], unique=False)

    op.create_table('company_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stock_id', sa.Integer(), nullable=False),
    sa.Column('emetteur_code', sa.String(length=64), nullable=True),
    sa.Column('emetteur_url', sa.Text(), nullable=True),
    sa.Column('company_name', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('business_model', sa.Text(), nullable=True),
    sa.Column('siege_social', sa.Text(), nullable=True),
    sa.Column('commissaire_aux_comptes', sa.Text(), nullable=True),
    sa.Column('date_constitution', sa.String(length=32), nullable=True),
    sa.Column('date_introduction', sa.String(length=32), nullable=True),
    sa.Column('duree_exercice_social', sa.String(length=32), nullable=True),
    sa.Column('ownership_json', sa.Text(), nullable=True),
    sa.Column('management_json', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('raw_payload', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['stock_id'], ['stocks.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stock_id', name='uq_company_profile_stock')
    )
    with op.batch_alter_table('company_profiles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_company_profiles_stock_id'), ['stock_id'], unique=False)

    op.create_table('favorites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stock_id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['stock_id'], ['stocks.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stock_id', name='uq_favorite_stock')
    )
    with op.batch_alter_table('favorites', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_favorites_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_favorites_stock_id'), ['stock_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_favorites_symbol'), ['symbol'], unique=False)

    op.create_table('fundamentals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stock_id', sa.Integer(), nullable=False),
    sa.Column('fiscal_year', sa.Integer(), nullable=False),
    sa.Column('eps', sa.Float(), nullable=True),
    sa.Column('roe_pct', sa.Float(), nullable=True),
    sa.Column('payout_pct', sa.Float(), nullable=True),
    sa.Column('dividend_yield_pct', sa.Float(), nullable=True),
    sa.Column('per', sa.Float(), nullable=True),
    sa.Column('pbr', sa.Float(), nullable=True),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('raw_payload', sa.Text(), nullable=True),
    sa.Column('collected_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['stock_id'], ['stocks.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stock_id', 'fiscal_year', 'source', name='uq_fundamental_year')
    )
    with op.batch_alter_table('fundamentals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fundamentals_fiscal_year'), ['fiscal_year'], unique=False)
        batch_op.create_index(batch_op.f('ix_fundamentals_stock_id'), ['stock_id'], unique=False)

    op.create_table('news',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stock_id', sa.Integer(), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('collected_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('source', sa.String(length=128), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=True),
    sa.Column('sentiment', sa.String(length=32), nullable=True),
    sa.Column('impact_score', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['stock_id'], ['stocks.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url', name='uq_news_url')
    )
    with op.batch_alter_table('news', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_news_stock_id'), ['stock_id'], unique=False)

    op.create_table('prices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stock_id', sa.Integer(), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('current_price', sa.Float(), nullable=True),
    sa.Column('daily_variation', sa.Float(), nullable=True),
    sa.Column('volume', sa.Float(), nullable=True),
    sa.Column('traded_quantity', sa.Float(), nullable=True),
    sa.Column('market_cap', sa.Float(), nullable=True),
    sa.Column('high_day', sa.Float(), nullable=True),
    sa.Column('low_day', sa.Float(), nullable=True),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('raw_payload', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['stock_id'], ['stocks.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stock_id', 'observed_at', 'source', name='uq_price_snapshot')
    )
    with op.batch_alter_table('prices', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_prices_observed_at'), ['observed_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_prices_stock_id'), ['stock_id'], unique=False)

    op.create_table('prediction_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('report_id', sa.Integer(), nullable=False),
    sa.Column('stock_id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('analyst', sa.String(length=32), nullable=False),
    sa.Column('horizon', sa.String(length=16), nullable=False),
    sa.Column('scenario', sa.String(length=64), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('evaluate_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('engine_version', sa.String(length=16), nullable=False),
    sa.Column('predicted_direction', sa.String(length=16), nullable=True),
    sa.Column('predicted_probability', sa.Float(), nullable=False),
    sa.Column('stated_confidence', sa.Float(), nullable=True),
    sa.Column('price_at_prediction', sa.Float(), nullable=True),
    sa.Column('evaluated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('price_at_evaluation', sa.Float(), nullable=True),
    sa.Column('realized_return', sa.Float(), nullable=True),
    sa.Column('realized_volatility', sa.Float(), nullable=True),
    sa.Column('realized_direction', sa.String(length=16), nullable=True),
    sa.Column('outcome', sa.Integer(), nullable=True),
    sa.Column('correct', sa.Integer(), nullable=True),
    sa.Column('brier_component', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['report_id'], ['analysis_reports.id'], ),
    sa.ForeignKeyConstraint(['stock_id'], ['stocks.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('report_id', 'analyst', 'horizon', 'scenario', name='uq_prediction_claim')
    )
    with op.batch_alter_table('prediction_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_prediction_history_analyst'), ['analyst'], unique=False)
        batch_op.create_index(batch_op.f('ix_prediction_history_evaluate_at'), ['evaluate_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_prediction_history_generated_at'), ['generated_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_prediction_history_horizon'), ['horizon'], unique=False)
        batch_op.create_index(batch_op.f('ix_prediction_history_report_id'), ['report_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_prediction_history_stock_id'), ['stock_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_prediction_history_symbol'), ['symbol'], unique=False)

    op.create_table('thesis_changes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stock_id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('horizon', sa.String(length=16), nullable=False),
    sa.Column('changed_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('previous_report_id', sa.Integer(), nullable=True),
    sa.Column('report_id', sa.Integer(), nullable=False),
    sa.Column('from_recommendation', sa.String(length=32), nullable=True),
    sa.Column('to_recommendation', sa.String(length=32), nullable=False),
    sa.Column('from_confidence', sa.Float(), nullable=True),
    sa.Column('to_confidence', sa.Float(), nullable=True),
    sa.Column('from_risk', sa.Float(), nullable=True),
    sa.Column('to_risk', sa.Float(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('new_evidence_json', sa.Text(), nullable=True),
    sa.Column('invalidated_json', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['previous_report_id'], ['analysis_reports.id'], ),
    sa.ForeignKeyConstraint(['report_id'], ['analysis_reports.id'], ),
    sa.ForeignKeyConstraint(['stock_id'], ['stocks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('thesis_changes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_thesis_changes_changed_at'), ['changed_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_thesis_changes_horizon'), ['horizon'], unique=False)
        batch_op.create_index(batch_op.f('ix_thesis_changes_report_id'), ['report_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_thesis_changes_stock_id'), ['stock_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_thesis_changes_symbol'), ['symbol'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('thesis_changes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_thesis_changes_symbol'))
        batch_op.drop_index(batch_op.f('ix_thesis_changes_stock_id'))
        batch_op.drop_index(batch_op.f('ix_thesis_changes_report_id'))
        batch_op.drop_index(batch_op.f('ix_thesis_changes_horizon'))
        batch_op.drop_index(batch_op.f('ix_thesis_changes_changed_at'))

    op.drop_table('thesis_changes')
    with op.batch_alter_table('prediction_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_prediction_history_symbol'))
        batch_op.drop_index(batch_op.f('ix_prediction_history_stock_id'))
        batch_op.drop_index(batch_op.f('ix_prediction_history_report_id'))
        batch_op.drop_index(batch_op.f('ix_prediction_history_horizon'))
        batch_op.drop_index(batch_op.f('ix_prediction_history_generated_at'))
        batch_op.drop_index(batch_op.f('ix_prediction_history_evaluate_at'))
        batch_op.drop_index(batch_op.f('ix_prediction_history_analyst'))

    op.drop_table('prediction_history')
    with op.batch_alter_table('prices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_prices_stock_id'))
        batch_op.drop_index(batch_op.f('ix_prices_observed_at'))

    op.drop_table('prices')
    with op.batch_alter_table('news', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_news_stock_id'))

    op.drop_table('news')
    with op.batch_alter_table('fundamentals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fundamentals_stock_id'))
        batch_op.drop_index(batch_op.f('ix_fundamentals_fiscal_year'))

    op.drop_table('fundamentals')
    with op.batch_alter_table('favorites', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_favorites_symbol'))
        batch_op.drop_index(batch_op.f('ix_favorites_stock_id'))
        batch_op.drop_index(batch_op.f('ix_favorites_created_at'))

    op.drop_table('favorites')
    with op.batch_alter_table('company_profiles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_company_profiles_stock_id'))

    op.drop_table('company_profiles')
    with op.batch_alter_table('company_knowledge', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_company_knowledge_stock_id'))
        batch_op.drop_index(batch_op.f('ix_company_knowledge_fact_hash'))
        batch_op.drop_index(batch_op.f('ix_company_knowledge_category'))

    op.drop_table('company_knowledge')
    with op.batch_alter_table('analysis_reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_analysis_reports_thesis_hash'))
        batch_op.drop_index(batch_op.f('ix_analysis_reports_symbol'))
        batch_op.drop_index(batch_op.f('ix_analysis_reports_stock_id'))
        batch_op.drop_index(batch_op.f('ix_analysis_reports_horizon_focus'))
        batch_op.drop_index(batch_op.f('ix_analysis_reports_generated_at'))
        batch_op.drop_index(batch_op.f('ix_analysis_reports_engine_version'))

    op.drop_table('analysis_reports')
    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_alerts_stock_id'))
        batch_op.drop_index(batch_op.f('ix_alerts_event_key'))
        batch_op.drop_index(batch_op.f('ix_alerts_alert_type'))

    op.drop_table('alerts')
    with op.batch_alter_table('stocks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stocks_symbol'))
        batch_op.drop_index(batch_op.f('ix_stocks_company_name'))

    op.drop_table('stocks')
    op.drop_table('push_subscriptions')
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notifications_created_at'))

    op.drop_table('notifications')
    with op.batch_alter_table('macro_indicators', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_macro_indicators_indicator'))
        batch_op.drop_index(batch_op.f('ix_macro_indicators_as_of'))

    op.drop_table('macro_indicators')
    with op.batch_alter_table('analyst_performance', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_analyst_performance_horizon'))
        batch_op.drop_index(batch_op.f('ix_analyst_performance_analyst'))

    op.drop_table('analyst_performance')
    # ### end Alembic commands ###
